# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='branch',
            new_name='roll_no',
        ),
    ]
