# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20170516_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=50)),
                ('q1', models.CharField(max_length=500)),
                ('q2', models.CharField(max_length=500)),
                ('q3', models.CharField(max_length=500)),
                ('q4', models.CharField(max_length=500)),
                ('q5', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='answers',
            name='appl_id',
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
